sensor = {
    "id": None,
    "name": None,
    "clazz": None,
    "savedAt": None,
    "oemId": None,
    "tenantId": None,
    "type": None,
    "timeZone": None,
    "secret": None,
    "smartExpression": None,
    "smartExpressionLayer": None,
    "smartScript": None,
    "smartScriptLayer": None,
    "deviceState": {
        "state": None,
        "message": None,
        "command": None,
        "errorCode": None,
        "deviceEvent": None
    },
    "appStateMachine": None,
    "appState": None,
    "location": None,
    "categories": {},
    "inCompoundSensor": False,
    "maxValue": None,
    "minValue": None,
    "valueUnit": None,
    "resolution": None,
    "resolutionUnit": None,
    "samplingRate": None,
    "samplingRateUnit": None,
    "lag": None,
    "lagUnit": None,
    "sensorProperties": []
}
